version: '3.8'

services:
  app:
    build: .
    container_name: medical-chat-backend
    ports:
      - '5050:5050'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev

  postgres:
    image: postgres:16
    container_name: medical-chat-db
    restart: always
    environment:
      POSTGRES_DB: darsh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
